//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Switcher.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Switcher: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Switcher()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Switcher"",
    ""maps"": [
        {
            ""name"": ""GearsO"",
            ""id"": ""22105eb2-6f33-4892-9ead-17e294c7df6a"",
            ""actions"": [
                {
                    ""name"": ""Switcher"",
                    ""type"": ""Value"",
                    ""id"": ""33681f93-b232-492a-91cc-cdf9f076e51b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gear 1"",
                    ""id"": ""48f9ac78-0298-4a0d-853a-045b128a3605"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""c72a5277-9d59-42ff-962e-6163962a8276"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6878d1ef-eae9-4b22-88bb-30c7ad7712dd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gear 2"",
                    ""id"": ""1f90603f-1b72-4c52-8f5f-da1003da7eb6"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4b2720dd-1251-425f-b042-475de6fd52c8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6cbe0606-8ad4-4ce4-91cb-b412bc363347"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gear 3"",
                    ""id"": ""ea2a889b-ec96-4338-9c3e-04f1692a4730"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4023191e-7692-4d87-bfe3-51e909a459b6"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0d0488ff-d460-4b0a-a514-cf7fc3611333"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d3617106-41c5-4172-840f-b920550d2a2a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gear 4"",
                    ""id"": ""ec24811d-e3a3-48b5-849b-c38c8b2ed3db"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""154f9fec-d1a5-4513-aa53-8c5b0b89786f"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""3c149ae2-54cd-41b6-a702-cb20f5a8dd74"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""12379342-2c23-410b-af90-e0069bb3e29b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Reverse"",
                    ""id"": ""be01510b-8670-4775-b22c-ec3c146e778c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7aa31575-d22f-4e1f-b8cc-8691143b0bba"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d274ce8d-3227-4d13-947d-3c13db2b1ff3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""05bb77c8-5746-4392-a4b9-a618b354fc4c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""655f549d-51d4-4b9f-8f4e-48161ca622d0"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""c00b8338-e6d2-4075-b772-83c4261ab2fb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""db248d79-ed53-4d1c-9969-c2178a1a3058"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Switcher"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Gears"",
            ""id"": ""f70e4022-a33d-4d1c-8b52-b92c3615d650"",
            ""actions"": [
                {
                    ""name"": ""Gear 1"",
                    ""type"": ""Value"",
                    ""id"": ""5f384d22-b35a-4731-af2d-899a9b9905df"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Gear 2"",
                    ""type"": ""Value"",
                    ""id"": ""741ff65a-aef3-4980-ba30-cb850ea9fba3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Gear 3"",
                    ""type"": ""Value"",
                    ""id"": ""755dae6a-8f5c-4f8d-923d-77abf4f9b122"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Gear 4"",
                    ""type"": ""Value"",
                    ""id"": ""2a0d5cdd-aac5-41dc-95fa-8e3b3295924a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reverse"",
                    ""type"": ""Value"",
                    ""id"": ""3c9cee4c-7731-4b6e-9a67-adb87daa3046"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""6b5fb179-e929-4997-b94d-74dfb4eae11b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""aa081cc3-23b9-44aa-a1a0-2c43dcee71a0"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""6bede9a2-3906-49f5-8a4d-8a2fcb659e64"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""f770581a-6e34-4dc9-b4b6-bbabe0fde60a"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""34ec0d9b-6dc6-4432-aed2-8b54f12eb182"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""8f7304a8-fe6d-4f63-b9e0-179edae71c08"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""067463aa-6125-4f86-be2e-23fdf7148d4c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""282079af-789f-46ef-b690-0b0c3276a12a"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a7f38e8a-aa70-402e-8d34-0c823663ffe8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""9df7ca79-13ab-46a2-907c-5e2f445cb119"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""a4bbe89a-642a-44bd-b8d3-39acea5cc6fc"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""c034fbd4-2561-4d8c-b04d-e9c76935b80e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""ee24d123-b75d-4d36-917b-3b5dd167f5a3"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reverse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""c81ffb40-4b0b-43f9-8a17-f854f391777a"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""73b38905-b03e-4f3c-98cd-4bc2b2d6e928"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GearsO
        m_GearsO = asset.FindActionMap("GearsO", throwIfNotFound: true);
        m_GearsO_Switcher = m_GearsO.FindAction("Switcher", throwIfNotFound: true);
        // Gears
        m_Gears = asset.FindActionMap("Gears", throwIfNotFound: true);
        m_Gears_Gear1 = m_Gears.FindAction("Gear 1", throwIfNotFound: true);
        m_Gears_Gear2 = m_Gears.FindAction("Gear 2", throwIfNotFound: true);
        m_Gears_Gear3 = m_Gears.FindAction("Gear 3", throwIfNotFound: true);
        m_Gears_Gear4 = m_Gears.FindAction("Gear 4", throwIfNotFound: true);
        m_Gears_Reverse = m_Gears.FindAction("Reverse", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GearsO
    private readonly InputActionMap m_GearsO;
    private List<IGearsOActions> m_GearsOActionsCallbackInterfaces = new List<IGearsOActions>();
    private readonly InputAction m_GearsO_Switcher;
    public struct GearsOActions
    {
        private @Switcher m_Wrapper;
        public GearsOActions(@Switcher wrapper) { m_Wrapper = wrapper; }
        public InputAction @Switcher => m_Wrapper.m_GearsO_Switcher;
        public InputActionMap Get() { return m_Wrapper.m_GearsO; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GearsOActions set) { return set.Get(); }
        public void AddCallbacks(IGearsOActions instance)
        {
            if (instance == null || m_Wrapper.m_GearsOActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GearsOActionsCallbackInterfaces.Add(instance);
            @Switcher.started += instance.OnSwitcher;
            @Switcher.performed += instance.OnSwitcher;
            @Switcher.canceled += instance.OnSwitcher;
        }

        private void UnregisterCallbacks(IGearsOActions instance)
        {
            @Switcher.started -= instance.OnSwitcher;
            @Switcher.performed -= instance.OnSwitcher;
            @Switcher.canceled -= instance.OnSwitcher;
        }

        public void RemoveCallbacks(IGearsOActions instance)
        {
            if (m_Wrapper.m_GearsOActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGearsOActions instance)
        {
            foreach (var item in m_Wrapper.m_GearsOActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GearsOActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GearsOActions @GearsO => new GearsOActions(this);

    // Gears
    private readonly InputActionMap m_Gears;
    private List<IGearsActions> m_GearsActionsCallbackInterfaces = new List<IGearsActions>();
    private readonly InputAction m_Gears_Gear1;
    private readonly InputAction m_Gears_Gear2;
    private readonly InputAction m_Gears_Gear3;
    private readonly InputAction m_Gears_Gear4;
    private readonly InputAction m_Gears_Reverse;
    public struct GearsActions
    {
        private @Switcher m_Wrapper;
        public GearsActions(@Switcher wrapper) { m_Wrapper = wrapper; }
        public InputAction @Gear1 => m_Wrapper.m_Gears_Gear1;
        public InputAction @Gear2 => m_Wrapper.m_Gears_Gear2;
        public InputAction @Gear3 => m_Wrapper.m_Gears_Gear3;
        public InputAction @Gear4 => m_Wrapper.m_Gears_Gear4;
        public InputAction @Reverse => m_Wrapper.m_Gears_Reverse;
        public InputActionMap Get() { return m_Wrapper.m_Gears; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GearsActions set) { return set.Get(); }
        public void AddCallbacks(IGearsActions instance)
        {
            if (instance == null || m_Wrapper.m_GearsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GearsActionsCallbackInterfaces.Add(instance);
            @Gear1.started += instance.OnGear1;
            @Gear1.performed += instance.OnGear1;
            @Gear1.canceled += instance.OnGear1;
            @Gear2.started += instance.OnGear2;
            @Gear2.performed += instance.OnGear2;
            @Gear2.canceled += instance.OnGear2;
            @Gear3.started += instance.OnGear3;
            @Gear3.performed += instance.OnGear3;
            @Gear3.canceled += instance.OnGear3;
            @Gear4.started += instance.OnGear4;
            @Gear4.performed += instance.OnGear4;
            @Gear4.canceled += instance.OnGear4;
            @Reverse.started += instance.OnReverse;
            @Reverse.performed += instance.OnReverse;
            @Reverse.canceled += instance.OnReverse;
        }

        private void UnregisterCallbacks(IGearsActions instance)
        {
            @Gear1.started -= instance.OnGear1;
            @Gear1.performed -= instance.OnGear1;
            @Gear1.canceled -= instance.OnGear1;
            @Gear2.started -= instance.OnGear2;
            @Gear2.performed -= instance.OnGear2;
            @Gear2.canceled -= instance.OnGear2;
            @Gear3.started -= instance.OnGear3;
            @Gear3.performed -= instance.OnGear3;
            @Gear3.canceled -= instance.OnGear3;
            @Gear4.started -= instance.OnGear4;
            @Gear4.performed -= instance.OnGear4;
            @Gear4.canceled -= instance.OnGear4;
            @Reverse.started -= instance.OnReverse;
            @Reverse.performed -= instance.OnReverse;
            @Reverse.canceled -= instance.OnReverse;
        }

        public void RemoveCallbacks(IGearsActions instance)
        {
            if (m_Wrapper.m_GearsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGearsActions instance)
        {
            foreach (var item in m_Wrapper.m_GearsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GearsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GearsActions @Gears => new GearsActions(this);
    public interface IGearsOActions
    {
        void OnSwitcher(InputAction.CallbackContext context);
    }
    public interface IGearsActions
    {
        void OnGear1(InputAction.CallbackContext context);
        void OnGear2(InputAction.CallbackContext context);
        void OnGear3(InputAction.CallbackContext context);
        void OnGear4(InputAction.CallbackContext context);
        void OnReverse(InputAction.CallbackContext context);
    }
}
